FROM ubuntu:18.04
MAINTAINER m_mandla@encs.concordia.ca

RUN apt-get update -y
RUN apt-get install python-pip -y
RUN apt-get install gunicorn3 -y

COPY requirement.txt requirement.txt
WORKDIR /opt/
COPY /opt/Inertia/

RUN pip3 install -r requirement.txt


CMD ["gunicorn3","-b","0.0.0.0/80","app:app","--workers=5"]
