FROM ubuntu:18.04
MAINTAINER m_mandla@encs.concordia.ca

RUN apt-get update -y
RUN apt-get install python-pip -y
RUN apt-get install gunicorn -y

COPY requirement.txt requirement.txt
WORKDIR /opt/
COPY . /opt/

RUN pip install -r requirement.txt


CMD ["gunicorn3","-b","0.0.0.0:8000","app:app","--workers=5"]
